dist: xenial
sudo: required

language: node_js
node_js:
  - "lts/*"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - npm i
  - hugo version # prints the Hugo version, just in case.
  - hugo # build the website
  - gulp minify

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.59.1