dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
before_script:
- npm i
script:
- hugo version
- hugo
- gulp minify
before_deploy:
- openssl aes-256-cbc -K $encrypted_a4f8dc998067_key -iv $encrypted_a4f8dc998067_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.59.1
  - secure: TCeqjnc8SZTZfYvEh6MFGhmJ3wEmOuB29qOcmnzK1MXLheGOIHpqaq41fVFC20KLaY7+nvtyLNTYZloPzG9AV9R26QwZ6fBiP/9FXFJkGyvdhonmOMjO7puoSws82gGFe7+zAxwrvbm3sl+Iq2sZ6f/99QbG0naGoqaDFAQtSMp73fWyibj5l+NNGJSfwTj3oViCfjqNA6I4oV7/5n264YusO61ivCA9ZlqeTzzIL8aoTHmsG2wjB20qLqJx6+62x20cMMeTaYrjE5qxi0K26MgW/oQiJSUI2BIRL7mtWmqJNHouC1+mWd6TCuV9fSYSwZDZa0sNlygagLgbSlNXYh4zD0HS8XJRBlY+aaa3DQ5nfBjTVsAuB2LmxBpdOpiVeFCjETXc0ctX2/tq8+SmWuPjnzq5cIxJ/Nki1n0LbJoVTy2y8XNrG18cCFauWNqzKdLz9YF7d45MLnnKnTpYnSa8nOYqHzoYgqP+K+tA4dv67Tk0y51uBTlf9dOwEOPPTs3SB6YATPmPUvEuXD86I2xzm0F/cbbYGD/Z2FVxPhEgT6rhVCRISOWK0lCNKdTEgalxwbRQU/amF0BKgEN+KsGv0Lws9SOyTb6hfBeNDyGCSAICADy4m8SxH10tTjmX/2MGzLE8xRL3ARAtepTrpjCpe5HP+WhrbIH3yPv3jtM=
  - secure: gEYpxbHeVmUog6X3C0vJ7cmuf4rPW4sE3O6PqZQhcubrNaqvhNQIncaTj1/GGImIOMFNATzlM8UrhhAierbGe699v3IyLqLahSsyPCxhaMQhiwGOeal2K63PFeUM/tcO97hSiczE7pWzDPnJZtp3KFCqRRox3dlTnczH4Mj8MNWKKXJDTNOVuhFEIsxjrq8NP7JRjrUHeI/HnRfmUtjHGWUmUSyOXF7lMZiF4HcROXbQRNKnOG06Ft/uzm+IobNd8qxjSKgfLKcBugtG/PBwRujpl7fFpYDsE6egPhGoFX0nP95WwbWyMqb+CLceaXDzIY42g1P7ZyQUQQmUdgFulkuWlmTtXNadmPL3hT1Nq8L4yHuBCdWi/hllX2Rd/Z+eCGF18PFZaHKuqK+kW6vIeh59zk3t7YTgN/r9bdfGMnQwwsgnwEN4PHpdrfQFdegK4dTBmm7eBNwUUkmbOlfz/VLEpaYTy05Sxbw3Vg8DTHbkKaAIYzHKZwZp6baJcbKPdeuDT7fcBRzKvyZdmBLDPt2Ez6mZpoiBnWKkd5MwekpMTlDjUpfiQ9NyJZKGVho9mj3eU/AZD+Oukp3lwBXygmTCp6WuXk4mqw2qY7fldYEZ5SJ3/0AHzfRFnwE10VMT0QxIH8fJUqBn53ETzP0Hze6/EUy6stcHyg8A3gOoRP0=
  - secure: xIiJ9bMi3lTxIa4EMx9YjQlKH2hwKw3CqWcnxS9QNDLKuGAHUoKlhInD9TmTIdkAYaFC4NFhLrUiO8BxLuvPxw6ofnggjEHYbGDxKydE5lPd5q/R64ruIN8KbYZTEVKwrsEUWp/f85q3cnLGWIS8Jt0GZ10sB5W3urIHHvgwZYvOi7Gfx9eEbQMXXbd299GAoC9BXZN9FPZ1AhilNq4UX5aclFYZCE8Y885p1kpVxFeipFlNWcNDXXixNUeYDXqw2RZbwyIg2BAjuR/tbMFJVVkCbuzk1Y60t0WPMt0lxsBe7pgPGeKK3FFYcAgJeKCJZoIY2qzFXooHtsB6ByFp13WqA6EvPpIJSieONFC/yG8sYpJTj1hDrtYg1PeN4RGMGrDG6NMdbElYDgTC3jGvTEDzqiDqb9vRjSjVpUU9dEh3FIFkXlQfYI7hPwe1p9H95esLVPm6B5+P6/mZx0jAyALek67PJzYPd6DBiMHvHZS9U8csCJt+mGlRUFl8LcwsIG8P1jY/mIPkTmUT37DDR79oZ75DKKuymbvbqaQ6ROtCwWjNzvPjQmECnASfvE22tUD723gXFw55wdyEOalXVEwNCNUQg/Atn/eCVn1mQbmyh3Vdifx0+g/zX+98Kt1cRbOID3e5aHZw3lFL1adzM9nzPLJAGe7yaPDdltax4rQ=
