# safelist
branches:
  only:
  - master
dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
before_script:
- npm i
script:
- hugo version
- hugo
- gulp minify
before_deploy:
- openssl aes-256-cbc -K $encrypted_a4f8dc998067_key -iv $encrypted_a4f8dc998067_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after --exclude "${TRAVIS_BUILD_DIR}/public/form" ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.60.1
  - secure: WkyWpz6KVX4kYr7GnmGWzHO5YwSYnt6zSaKgeCeKFyOaMNNt6veu5THeG0kF/T0EC4/zojp5tLmpDYu6kbDpB9pYxgTtRI+SwLx9VquE6vgIIQzEV/Esi1LRoPvZ9St9Xbh1bG7Y4yfZUzIlXn/uqXywvWc1Y3OR7Nwwtvx8mIPCNtyZO+l4hKYIr8OtKQFjmHKiKtQEDPhPswSvezdjuM1cgXqmHBUUHx9FYPrPT9fXI6kC2XoRkPWgfqFOKWtRhKwXRUJzN860fnCVzuO4axyv0mUZm1C+dsNk+438WznhZRvgSLSqhbEA6MSjeoAyZ1lgnSXDv6AltEOEpWyNCe4WHUAftjfFhae80Jed7ZEPejPmV3IMujjBKRJLxUxTSnB984Xsnkh75U5AqZiQXwvkQpTRB/79f9iBEFoW+TcbXMxNuQKWmF4nCYbCYZZqfHfBTRoBQod+Z7be99RhbiN64CYyVYiSjzjaeHHbCk2DnNEBiepe4xgQgkKeo3qm6Iw4R2B9jHty91JjUgqSYg7ukJvFaQma0agxe7MxbkPiy8EO3HxLTsIpUsytqusnmooCu5cR+pVcX+xUaUqriFtg/6g6cJ9lavsvv0WthGqmRtzmINNj/9HkW4lUEN2oxgpvQy88bNovLcmuT9pvKoBINrkHm6Ri9ySkW7qHxUQ=
  - secure: F7jmDWoqMwG0nSk3Gs29LPlrKst4mrI+fA4sGzM5D51NUBy/U/guRx//UFsO2O1rvio0bVL7QElh5i+eBXCfR13u4S6Qe7ogYUI5o3VtpVUS5QqOFaKuAnkOoICH7YX5a3uUBqBhwpxLA/kF6oEFsd1gLO0+49N4xgBd78lbNQLWGQXUntUmIw3oKBkRhOQ/p56WuAM49iEyvMEOJxL0N3h4n1E679/f3cMvumoOmdYcuv4pmkH/Oljl7IGOi4cGg5OUjDtnNaHWnmTW3455ToFmuRuqi5A2EQ/22JYYBlOk6cZYXJGyadSihth2CpGX82ozcWLrZutEluFyOyyPkQRXsADANtyCV19WIxVaUZm3gCyT2BgCbkvTUEH3B98/JL94xqldKlYxOD0BG4+0/FEehmb4/KdH6IHM/URIdu/TOIX+3cVISqmZQkoWP7wXc6ap3dUAkuET0WbEi0TJEUgC0/CjVNXxGW1P+v9Y2K2Np0Qle2wrMrIM293YQHB6UQkO5QzfDyBZWodyTM1gssGzJBwUiJ8G4MSAa6dmNB6kjosXVBeDglLWUQbp8Y7y0N88R/QonqFZRvV1IdKmVFoa+CmwqNP55yA5MXIywcpJjkdaB5mKg3cKKSFlpdUkLgIPPTcouTtr9rRfcVb+OBXiY/wT2KDMxwxEqRjkxmk=
  - secure: qz5sHYHhngeCv2QlheRF6Ng8j3n6l+hD9XTeSpL7H8Z1EX4jEs91XFRfRjhpiiE6lMPMNID0EPafjPJKsFOY0A+1KSx5Uzo6d6beOExJpbVNxr3LIiwiEyH2Fluu3KGHxpekDWqn0uy2hcGK2J9pGuihZyoxQY1vfeuqNPDFuVBYEUJJWMcvf2uZuA5tYSLk1n04OQfj5Dp/zV35hnbONylDv+Q3P22kHWpwZHYJ8Lsxlm4Ygekqr1GHpPWD+Ks3KOryAQ3N8g4hBZ0+4rXxzps9CEhBXphxt8pYITFauxXVVGqNMe5KjDuyqvPcC73jKRBH/Ei8yJchNe+bn5uUVfx02fElx2u8M2tXf+cKO0r0a2uoQalE7On45Z3xfCxwQW9tQuu6p1pgtufIFMWOhSPXh1y5wz+ZfAaJsBKLaXaj7Z8Kpoa2Z1M9Sal59FreRorOig8xIUizCUJiwajDXupBlJdM58KB2TQ+HPwPh2vQim648MGxqimpmKQ2mM2UzwNHs1mufqeYB5Awsacs1phkCHg1BztdjSwrCFIdhel/rpwKRx3W4vV+wQwo4l2Ef32g/oJUEGRvUeQ5NlnfMFs18ThgO6RnUNSk1bzE+azIqA+jTHBHh6+UMY+aFT49tSNOsvhABWpNCqEdIRN0C1OrWr49thsS2SxEcvlHMKI=
notifications:
  email:
    recipients:
      - bonjour@studiocolibri.be
    on_success: never # default: change
    on_failure: always # default: always
